/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaInterfaz;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Erick Perez
 */
public class WinCarga extends javax.swing.JFrame {

    /**
     * Creates new form WinGeneral
     */
    ActionListener ac;
    int x=0;
    Timer t;
    
    public WinCarga() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 476);
        ac=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x=x+1;
                ItBarra.setValue(x);
                if(ItBarra.getValue()==30){
                    txtMensaje.setText("Va progresando...");
                }
                if(ItBarra.getValue()==70){
                    txtMensaje.setText("Ya mismo termina...");
                }
                if(ItBarra.getValue()==100){
                    WinGeneral b = new WinGeneral();
                    b.setVisible(true);
                    dispose();
                }
            }
        };
        t=new Timer(50,ac);
        t.start();
        UIManager.put("nimbusOrange", new Color(0, 160, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        ItBarra = new javax.swing.JProgressBar();
        txtMensaje = new javax.swing.JLabel();
        imgInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItBarra.setMaximum(101);
        content.add(ItBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 540, 30));

        txtMensaje.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));
        txtMensaje.setText("Cargando...");
        content.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 540, 30));

        imgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaImagenes/NutraPro.png"))); // NOI18N
        content.add(imgInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ItBarra;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgInicio;
    private javax.swing.JLabel txtMensaje;
    // End of variables declaration//GEN-END:variables
}
