/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaInterfaz;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Erick Perez
 */
public class WinIngresosPila extends javax.swing.JPanel {

    /**
     * Creates new form WinNuevosPacientesCola
     */
    public WinIngresosPila() {
        initComponents();
        setSize(720, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JPanel();
        txtIngresar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmpRaza = new javax.swing.JTextField();
        cmpNombreM = new javax.swing.JTextField();
        cmpNomDue = new javax.swing.JTextField();
        chkMacho = new javax.swing.JCheckBox();
        chkHembra = new javax.swing.JCheckBox();
        txtRaza = new javax.swing.JLabel();
        txtNomDue = new javax.swing.JLabel();
        txtNomMas = new javax.swing.JLabel();
        cmpPeso = new javax.swing.JTextField();
        txtPeso = new javax.swing.JLabel();
        cmpEdad = new javax.swing.JTextField();
        txtEdad = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        cmpTelefono = new javax.swing.JTextField();
        cmpId = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        cmpCosto = new javax.swing.JTextField();
        txtCosto = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });

        txtIngresar.setBackground(new java.awt.Color(255, 255, 255));
        txtIngresar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtIngresar.setForeground(new java.awt.Color(0, 0, 0));
        txtIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIngresar.setText("Ingresar");

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        btnIngresarLayout.setVerticalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        content.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        txtEliminar.setBackground(new java.awt.Color(255, 255, 255));
        txtEliminar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(0, 0, 0));
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 140, 50));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 150, 400));
        content.add(cmpRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));
        content.add(cmpNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, -1));
        content.add(cmpNomDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 120, -1));

        chkMacho.setForeground(new java.awt.Color(0, 0, 0));
        chkMacho.setText("Hembra");
        content.add(chkMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        chkHembra.setForeground(new java.awt.Color(0, 0, 0));
        chkHembra.setText("Macho");
        content.add(chkHembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtRaza.setBackground(new java.awt.Color(0, 0, 0));
        txtRaza.setForeground(new java.awt.Color(0, 0, 0));
        txtRaza.setText("Raza:");
        content.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        txtNomDue.setBackground(new java.awt.Color(0, 0, 0));
        txtNomDue.setForeground(new java.awt.Color(0, 0, 0));
        txtNomDue.setText("Nombre Dueño:");
        content.add(txtNomDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 20));

        txtNomMas.setBackground(new java.awt.Color(0, 0, 0));
        txtNomMas.setForeground(new java.awt.Color(0, 0, 0));
        txtNomMas.setText("Nombre Mascota:");
        content.add(txtNomMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));
        content.add(cmpPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, -1));

        txtPeso.setBackground(new java.awt.Color(0, 0, 0));
        txtPeso.setForeground(new java.awt.Color(0, 0, 0));
        txtPeso.setText("Peso Mascota:");
        content.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));
        content.add(cmpEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, -1));

        txtEdad.setBackground(new java.awt.Color(0, 0, 0));
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));
        txtEdad.setText("Edad:");
        content.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

        txtTelefono.setBackground(new java.awt.Color(0, 0, 0));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Telefono:");
        content.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 20));
        content.add(cmpTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, -1));
        content.add(cmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 120, -1));

        txtId.setBackground(new java.awt.Color(0, 0, 0));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setText("ID:");
        content.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));
        content.add(cmpCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 120, -1));

        txtCosto.setBackground(new java.awt.Color(0, 0, 0));
        txtCosto.setForeground(new java.awt.Color(0, 0, 0));
        txtCosto.setText("Costo:");
        content.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, 20));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaImagenes/fondo.png"))); // NOI18N
        content.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new Color(0, 160, 230));
        txtIngresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        btnIngresar.setBackground(Color.WHITE);
        txtIngresar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(0, 160, 230));
        txtEliminar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(Color.WHITE);
        txtEliminar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEliminarMouseExited

    public JPanel getContent() {
        return content;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JCheckBox chkHembra;
    private javax.swing.JCheckBox chkMacho;
    private javax.swing.JTextField cmpCosto;
    private javax.swing.JTextField cmpEdad;
    private javax.swing.JTextField cmpId;
    private javax.swing.JTextField cmpNomDue;
    private javax.swing.JTextField cmpNombreM;
    private javax.swing.JTextField cmpPeso;
    private javax.swing.JTextField cmpRaza;
    private javax.swing.JTextField cmpTelefono;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtIngresar;
    private javax.swing.JLabel txtNomDue;
    private javax.swing.JLabel txtNomMas;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtRaza;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
