/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaInterfaz;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Erick Perez
 */
public class WinPacientesListEst extends javax.swing.JPanel {

    /**
     * Creates new form WinNuevosPacientesCola
     */
    public WinPacientesListEst() {
        initComponents();
        setSize(720, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnVisualizar = new javax.swing.JPanel();
        txtVisualizar = new javax.swing.JLabel();
        btnSalida = new javax.swing.JPanel();
        txtSalida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnOrdenar = new javax.swing.JPanel();
        txtOrdenar = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseExited(evt);
            }
        });

        txtVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        txtVisualizar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtVisualizar.setForeground(new java.awt.Color(0, 0, 0));
        txtVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVisualizar.setText("Visualizar");

        javax.swing.GroupLayout btnVisualizarLayout = new javax.swing.GroupLayout(btnVisualizar);
        btnVisualizar.setLayout(btnVisualizarLayout);
        btnVisualizarLayout.setHorizontalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        btnVisualizarLayout.setVerticalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        content.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 50));

        btnSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalidaMouseExited(evt);
            }
        });

        txtSalida.setBackground(new java.awt.Color(255, 255, 255));
        txtSalida.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtSalida.setForeground(new java.awt.Color(0, 0, 0));
        txtSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalida.setText("Marcar salida");

        javax.swing.GroupLayout btnSalidaLayout = new javax.swing.GroupLayout(btnSalida);
        btnSalida.setLayout(btnSalidaLayout);
        btnSalidaLayout.setHorizontalGroup(
            btnSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        btnSalidaLayout.setVerticalGroup(
            btnSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        content.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 50));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 290, 400));

        jComboBox1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Costo", "Peso" }));
        content.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 190, 30));

        btnOrdenar.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseExited(evt);
            }
        });

        txtOrdenar.setBackground(new java.awt.Color(255, 255, 255));
        txtOrdenar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        txtOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOrdenar.setText("Ordenar");

        javax.swing.GroupLayout btnOrdenarLayout = new javax.swing.GroupLayout(btnOrdenar);
        btnOrdenar.setLayout(btnOrdenarLayout);
        btnOrdenarLayout.setHorizontalGroup(
            btnOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        btnOrdenarLayout.setVerticalGroup(
            btnOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        content.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 200, 50));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaImagenes/fondo.png"))); // NOI18N
        content.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseEntered
        btnVisualizar.setBackground(new Color(0, 160, 230));
        txtVisualizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVisualizarMouseEntered

    private void btnVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseExited
        btnVisualizar.setBackground(Color.WHITE);
        txtVisualizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnVisualizarMouseExited

    private void btnSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseEntered
        btnSalida.setBackground(new Color(0, 160, 230));
        txtSalida.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalidaMouseEntered

    private void btnSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseExited
        btnSalida.setBackground(Color.WHITE);
        txtSalida.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSalidaMouseExited

    private void btnOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseEntered
        btnOrdenar.setBackground(new Color(0, 160, 230));
        txtOrdenar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnOrdenarMouseEntered

    private void btnOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseExited
        btnOrdenar.setBackground(Color.WHITE);
        txtOrdenar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnOrdenarMouseExited

    public JPanel getContent() {
        return content;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnOrdenar;
    private javax.swing.JPanel btnSalida;
    private javax.swing.JPanel btnVisualizar;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txtOrdenar;
    private javax.swing.JLabel txtSalida;
    private javax.swing.JLabel txtVisualizar;
    // End of variables declaration//GEN-END:variables
}
