/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaInterfaz;

import EstEnlacesDobles.ClsListDim2;
import EstEnlacesDobles.ClsNodo2;
import java.awt.Color;
import EstArbol.*;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Erick Perez
 */
public class WinVisualizarGrafo extends javax.swing.JPanel {

    ClsListDim2 lista;
    ClsArboles arbol = new ClsArboles();
    
    /**
     * Creates new form WinVisualizarGrafo
     */
    public WinVisualizarGrafo(ClsListDim2   list) {
        initComponents();
        setSize(720, 530);
        this.lista = list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmpRes = new javax.swing.JTextArea();
        btnPostOrden = new javax.swing.JPanel();
        txtPostOrden = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JPanel();
        txtVisualizar = new javax.swing.JLabel();
        btnPreOrden = new javax.swing.JPanel();
        txtPreOrden = new javax.swing.JLabel();
        btnInOrden = new javax.swing.JPanel();
        txtInOrden = new javax.swing.JLabel();
        txtArbol = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desktop.setPreferredSize(new java.awt.Dimension(500, 500));

        jInternalFrame2.setPreferredSize(new java.awt.Dimension(500, 500));
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        Desktop.setLayer(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        content.add(Desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 400, 450));

        cmpRes.setEditable(false);
        cmpRes.setColumns(20);
        cmpRes.setRows(5);
        cmpRes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(cmpRes);

        content.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 260, 110));

        btnPostOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnPostOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPostOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPostOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPostOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPostOrdenMouseExited(evt);
            }
        });

        txtPostOrden.setBackground(new java.awt.Color(255, 255, 255));
        txtPostOrden.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtPostOrden.setForeground(new java.awt.Color(0, 0, 0));
        txtPostOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPostOrden.setText("InOrden");
        txtPostOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPostOrdenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPostOrdenLayout = new javax.swing.GroupLayout(btnPostOrden);
        btnPostOrden.setLayout(btnPostOrdenLayout);
        btnPostOrdenLayout.setHorizontalGroup(
            btnPostOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPostOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPostOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPostOrdenLayout.setVerticalGroup(
            btnPostOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPostOrdenLayout.createSequentialGroup()
                .addComponent(txtPostOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btnPostOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 40));

        btnVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseExited(evt);
            }
        });

        txtVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        txtVisualizar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtVisualizar.setForeground(new java.awt.Color(0, 0, 0));
        txtVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVisualizar.setText("Visualizar");
        txtVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVisualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnVisualizarLayout = new javax.swing.GroupLayout(btnVisualizar);
        btnVisualizar.setLayout(btnVisualizarLayout);
        btnVisualizarLayout.setHorizontalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVisualizarLayout.setVerticalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisualizarLayout.createSequentialGroup()
                .addComponent(txtVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 160, 40));

        btnPreOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnPreOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPreOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPreOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPreOrdenMouseExited(evt);
            }
        });

        txtPreOrden.setBackground(new java.awt.Color(255, 255, 255));
        txtPreOrden.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtPreOrden.setForeground(new java.awt.Color(0, 0, 0));
        txtPreOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPreOrden.setText("PreOrden");
        txtPreOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPreOrdenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPreOrdenLayout = new javax.swing.GroupLayout(btnPreOrden);
        btnPreOrden.setLayout(btnPreOrdenLayout);
        btnPreOrdenLayout.setHorizontalGroup(
            btnPreOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPreOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPreOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPreOrdenLayout.setVerticalGroup(
            btnPreOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPreOrdenLayout.createSequentialGroup()
                .addComponent(txtPreOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btnPreOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 40));

        btnInOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnInOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInOrdenMouseExited(evt);
            }
        });

        txtInOrden.setBackground(new java.awt.Color(255, 255, 255));
        txtInOrden.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtInOrden.setForeground(new java.awt.Color(0, 0, 0));
        txtInOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInOrden.setText("InOrden");
        txtInOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInOrdenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnInOrdenLayout = new javax.swing.GroupLayout(btnInOrden);
        btnInOrden.setLayout(btnInOrdenLayout);
        btnInOrdenLayout.setHorizontalGroup(
            btnInOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnInOrdenLayout.setVerticalGroup(
            btnInOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInOrdenLayout.createSequentialGroup()
                .addComponent(txtInOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(btnInOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 160, 40));

        txtArbol.setForeground(new java.awt.Color(0, 0, 0));
        txtArbol.setText("Datos del arbol:");
        content.add(txtArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaImagenes/fondo.png"))); // NOI18N
        imgFondo.setText("jLabel1");
        content.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPostOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPostOrdenMouseClicked
        cmpRes.setText("");
        cmpRes.setText(arbol.postOrden());
    }//GEN-LAST:event_txtPostOrdenMouseClicked

    private void btnPostOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostOrdenMouseEntered
        btnPostOrden.setBackground(new Color(0, 160, 230));
        txtPostOrden.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPostOrdenMouseEntered

    private void btnPostOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostOrdenMouseExited
        btnPostOrden.setBackground(Color.WHITE);
        txtPostOrden.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnPostOrdenMouseExited

    private void txtVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVisualizarMouseClicked
        ClsNodo2 otro= new ClsNodo2();
        otro = lista.cabizq();
        for (int i = 1; otro.enlder()!= null; i++){
            ClsNodo nodo = new ClsNodo(otro.inf());
            arbol.insertar(nodo , arbol.getRaiz());
            this.repintarArbol();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(WinVisualizarGrafo.class.getName()).log(Level.SEVERE, null, ex);
            }
            otro = otro.enlder();
        }
    }//GEN-LAST:event_txtVisualizarMouseClicked

    private void btnVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseEntered
        btnVisualizar.setBackground(new Color(0, 160, 230));
        txtVisualizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVisualizarMouseEntered

    private void btnVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseExited
        btnVisualizar.setBackground(Color.WHITE);
        txtVisualizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnVisualizarMouseExited

    private void txtPreOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPreOrdenMouseClicked
        cmpRes.setText("");
        cmpRes.setText(arbol.preOrden());
    }//GEN-LAST:event_txtPreOrdenMouseClicked

    private void btnPreOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreOrdenMouseEntered
        btnPreOrden.setBackground(new Color(0, 160, 230));
        txtPreOrden.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPreOrdenMouseEntered

    private void btnPreOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreOrdenMouseExited
        btnPreOrden.setBackground(Color.WHITE);
        txtPreOrden.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnPreOrdenMouseExited

    private void txtInOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInOrdenMouseClicked
        cmpRes.setText("");
        cmpRes.setText(arbol.inOrden());
    }//GEN-LAST:event_txtInOrdenMouseClicked

    private void btnInOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInOrdenMouseEntered
        btnInOrden.setBackground(new Color(0, 160, 230));
        txtInOrden.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnInOrdenMouseEntered

    private void btnInOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInOrdenMouseExited
        btnInOrden.setBackground(Color.WHITE);
        txtInOrden.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnInOrdenMouseExited

    private void repintarArbol() {
        this.Desktop.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación gráfica del arbol de precios", false);
        this.Desktop.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        this.jInternalFrame2.add(this.arbol.getdibujo(), BorderLayout.CENTER);
    }

    public JPanel getContent() {
        return content;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JPanel btnInOrden;
    private javax.swing.JPanel btnPostOrden;
    private javax.swing.JPanel btnPreOrden;
    private javax.swing.JPanel btnVisualizar;
    private javax.swing.JTextArea cmpRes;
    private javax.swing.JPanel content;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtArbol;
    private javax.swing.JLabel txtInOrden;
    private javax.swing.JLabel txtPostOrden;
    private javax.swing.JLabel txtPreOrden;
    private javax.swing.JLabel txtVisualizar;
    // End of variables declaration//GEN-END:variables
}
